entregaFinal/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from . import views

app_name='blog'

urlpatterns = [
    path('', views.home, name="Home"),
    path('registrar/', views.registrar, name='registrarUsuario'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('publicacion/', views.crearPublicacion, name='crearPublicacion' ), 
    path('publicaciones/', views.mostrarPublicaciones, name='verPublicaciones'),
    path('publicacion/<int:pk>/', views.detallePublicacion, name='detallePublicacionPK'),
    path('publicacion/<int:pk>/comentar/', views.agregarComentario, name='agregarComentario'),
    path('comentario/<int:pk>/eliminar/', views.eliminarComentario, name='eliminarComentario'),
    path('comentario/<int:pk>/editar/', views.editarComentario, name='editarComentario'),
    path('filtrarPublicaciones/', views.filtrarPublicaciones, name="filtraPublicaciones"),
    path('perfil/', views.perfil, name='perfil'),
    path('actualizarPerfil/', views.actualizarPerfil, name='actualizarPerfil'),
    path('publicacion/<int:publicacion_id>/eliminar/', views.eliminar_publicacion, name='eliminarPublicacion'),
    path('about/', views.about ,name='about'),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

entregaFinal/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls") )
]

entregaFinal/blog/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.conf import settings

from django.contrib.auth.models import BaseUserManager

class Usuario(AbstractUser):
    image_profile = models.ImageField(upload_to='profile_images', blank=True, null=True)
    
    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to.',
        related_name='usuarios'  # Agrega el related_name para evitar el conflicto
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name='usuarios'  # Agrega el related_name para evitar el conflicto
    )
    def __str__(self):
        return self.username
    
class Publicacion(models.Model):
    titulo = models.CharField(max_length=200)
    fecha = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    cuerpo = models.TextField()
    imagen_portada = models.ImageField(upload_to='portadas', blank=True, null=True)


class Comentario(models.Model):
    publicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE, related_name='comentarios')
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    contenido = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)

entregaFinal/blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Publicacion, Usuario
from django.db import models
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
 
class RegistrarForm(forms.ModelForm):
    username = forms.CharField(label='Username')
    password1 = forms.CharField(label='Password')
    password2 = forms.CharField(label='Confirm Password')
    email = forms.EmailField(label='Email')
    profile_image = forms.ImageField(required=False)
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email', 'profile_image')

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Las contraseñas no coinciden')
        return password2
    
class PublicacionForm(forms.ModelForm):
    titulo = forms.CharField(label='Titulo', widget=forms.TextInput(attrs={'class': 'centered-input'}))
    cuerpo = forms.CharField(label='Cuerpo', widget=forms.TextInput(attrs={'class': 'centered-input'}))
    imagen_portada = forms.ImageField(label='Imagen portada', required=False)
    class Meta:
        model = Publicacion
        fields = ['titulo', 'cuerpo', 'imagen_portada']

class PerfilUsuarioForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

entregaFinal/blog/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.http import HttpResponseRedirect, JsonResponse
from django.middleware.csrf import get_token
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import PerfilUsuarioForm, PublicacionForm, RegistrarForm
from .models import Comentario, Publicacion, Usuario

app_name='blog'

def home(request):
    login_error = request.COOKIES.get('login_error')
    if login_error:
        context = {'login_error': login_error}
    else:
        context = {}
    return render(request, 'home.html', context)


def registrar(request):
    if request.method == 'POST':
        form = RegistrarForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.password = make_password(form.cleaned_data['password1'])
            user.save()
            messages.success(request, 'Usuario creado correctamente.')
            return redirect('blog:Home')  # Redireccionar a la página de inicio
        else:
            # Agregar mensaje de error al campo de confirmación de contraseña
            form.add_error('password2', 'Las contraseñas no coinciden')
    else:
        form = RegistrarForm()
    return render(request, 'registrar.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url) 
            else:
                return redirect('Home')
        else:
            return HttpResponseRedirect(reverse('blog:Home') + '?login_error=Credenciales inválidas. Inténtalo de nuevo.')

    return JsonResponse({'success': False, 'message': 'Acceso no permitido.'})


def logout_view(request):
    logout(request)
    return redirect('blog:Home')  

@login_required
def crearPublicacion(request):
    if request.method == 'POST':
        form = PublicacionForm(request.POST, request.FILES)
        if form.is_valid():
            titulo = form.cleaned_data['titulo']
            cuerpo = form.cleaned_data['cuerpo']
            imagen_portada = form.cleaned_data['imagen_portada']
            publicacion = Publicacion(titulo=titulo, cuerpo=cuerpo, autor=request.user, imagen_portada=imagen_portada)
            publicacion.save()
            return redirect('blog:verPublicaciones')
    else:
        form = PublicacionForm(initial={'csrfmiddlewaretoken': get_token(request)})
    
    return render(request, 'publicacion.html')



def mostrarPublicaciones(request):
    publicaciones = Publicacion.objects.all()
    return render(request, 'publicaciones.html', {'publicaciones': publicaciones})


def detallePublicacion(request, pk):
    publicacion = get_object_or_404(Publicacion, pk=pk)
    return render(request, 'detallePublicacion.html', {'publicacion': publicacion})

@login_required
def agregarComentario(request, pk):
    publicacion = get_object_or_404(Publicacion, pk=pk)
    contenido = request.POST.get('contenido')
    autor = request.user

    if contenido:
        comentario = Comentario(publicacion=publicacion, autor=autor, contenido=contenido)
        comentario.save()

    next_url = request.POST.get('next')
    if next_url:
        return redirect(next_url)
    else:
        publicaciones = Publicacion.objects.all()
        return render(request, 'publicaciones.html', {'publicaciones': publicaciones})


@login_required
def eliminarComentario(request, pk):
    comentario = get_object_or_404(Comentario, pk=pk)
    if comentario.autor == request.user:
        comentario.delete()
        messages.success(request, 'Comentario eliminado correctamente.')
    else:
        messages.error(request, 'No tienes permiso para eliminar este comentario.')
    
    return redirect(request.META.get('HTTP_REFERER', 'Home'))

@login_required
def editarComentario(request, pk):
    comentario = get_object_or_404(Comentario, pk=pk)

    if request.method == 'POST':
        contenido = request.POST.get('contenido')
        if contenido:
            comentario.contenido = contenido
            comentario.save()
            messages.success(request, 'Comentario actualizado correctamente.')
        else:
            messages.error(request, 'El contenido del comentario no puede estar vacío.')

    return redirect('detallePublicacion', pk=comentario.publicacion.pk)


def filtrarPublicaciones(request):
    query = request.GET.get('q') 
    if query:
        publicaciones = Publicacion.objects.filter(titulo__icontains=query) | Publicacion.objects.filter(cuerpo__icontains=query) | Publicacion.objects.filter(autor__username__icontains=query)
    else:
        publicaciones = Publicacion.objects.all()
    return render(request, 'publicaciones.html', {'publicaciones': publicaciones})

@login_required
def perfil(request):
    user = request.user

    if request.method == 'POST':
        form = PerfilUsuarioForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('perfil')  
    else:
        form = PerfilUsuarioForm(instance=user)

    return render(request, 'perfil.html', {'form': form})

@login_required
def actualizarPerfil(request):
    if request.method == 'POST':
        # Obtener los datos del formulario
        email = request.POST['email']
        password = request.POST['password1']

        # Actualizar los datos del usuario
        user = request.user
        user.email = email
        if password:
            user.set_password(password)
        user.save()
        messages.success(request, 'Datos actualizados')
        
    else:
        messages.error(request, 'Datos no actualizados')
    
    return render(request, 'perfil.html')

@login_required
def eliminar_publicacion(request, publicacion_id):
    publicacion = Publicacion.objects.get(id=publicacion_id)
    if request.user == publicacion.autor:
        publicacion.delete()
        messages.success(request, 'Publicación eliminada.')
    else:
        messages.error(request, 'No tienes permiso para eliminar esta publicación.')
    
    return redirect(request.META.get('HTTP_REFERER', 'Home'))

def about(request):
    return render(request, 'about.html')

entregaFinal/blog/templates/components/footer.html
<footer class="footer border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">Copyright &copy; Julio Villagra 2023</div>
            </div>
        </div>
    </div>
</footer>

entregaFinal/blog/templates/components/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-info" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand text-light" href="{% url 'blog:Home' %}">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <div class="ms-auto">
                {% if user.is_authenticated %}
                    <span class="navbar-text me-2">¡Bienvenido, {{ user.username }}!</span>
                   
                    <a href="{% url 'blog:perfil' %}"><button type="button" class="btn btn-success">Mi perfil</button></a>
                    <a href="{% url 'blog:logout' %}"><button type="button" class="btn btn-danger">Cerrar sesión</button></a>
                {% else %}
                    <a href="{% url 'blog:about' %}"><button type="button" class="btn btn-warning">About</button></a>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#loginModal">Iniciar sesión</button>
                {% endif %}
            </div>
        </div>
    </div>
</nav>