entregaFinal/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from . import views

app_name='blog'

urlpatterns = [
    path('', views.home, name="Home"),
    path('registrar/', views.registrar, name='registrarUsuario'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('publicacion/', views.crearPublicacion, name='crearPublicacion' ), 
    path('publicaciones/', views.mostrarPublicaciones, name='verPublicaciones'),
    path('publicacion/<int:pk>/', views.detallePublicacion, name='detallePublicacionPK'),
    path('publicacion/<int:pk>/comentar/', views.agregarComentario, name='agregarComentario'),
    path('comentario/<int:pk>/eliminar/', views.eliminarComentario, name='eliminarComentario'),
    path('comentario/<int:pk>/editar/', views.editarComentario, name='editarComentario'),
    path('filtrarPublicaciones/', views.filtrarPublicaciones, name="filtraPublicaciones"),
    path('perfil/', views.perfil, name='perfil'),
    path('actualizarPerfil/', views.actualizarPerfil, name='actualizarPerfil'),
    path('publicacion/<int:publicacion_id>/eliminar/', views.eliminar_publicacion, name='eliminarPublicacion'),
    path('about/', views.about ,name='about'),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

entregaFinal/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls") )
]

entregaFinal/blog/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.conf import settings

from django.contrib.auth.models import BaseUserManager

class Usuario(AbstractUser):
    image_profile = models.ImageField(upload_to='profile_images', blank=True, null=True)
    
    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to.',
        related_name='usuarios'  # Agrega el related_name para evitar el conflicto
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name='usuarios'  # Agrega el related_name para evitar el conflicto
    )
    def __str__(self):
        return self.username
    
class Publicacion(models.Model):
    titulo = models.CharField(max_length=200)
    fecha = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    cuerpo = models.TextField()
    imagen_portada = models.ImageField(upload_to='portadas', blank=True, null=True)


class Comentario(models.Model):
    publicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE, related_name='comentarios')
    autor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    contenido = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)

entregaFinal/blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Publicacion, Usuario
from django.db import models
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
 
class RegistrarForm(forms.ModelForm):
    username = forms.CharField(label='Username')
    password1 = forms.CharField(label='Password')
    password2 = forms.CharField(label='Confirm Password')
    email = forms.EmailField(label='Email')
    profile_image = forms.ImageField(required=False)
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email', 'profile_image')

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Las contraseñas no coinciden')
        return password2
    
class PublicacionForm(forms.ModelForm):
    titulo = forms.CharField(label='Titulo', widget=forms.TextInput(attrs={'class': 'centered-input'}))
    cuerpo = forms.CharField(label='Cuerpo', widget=forms.TextInput(attrs={'class': 'centered-input'}))
    imagen_portada = forms.ImageField(label='Imagen portada', required=False)
    class Meta:
        model = Publicacion
        fields = ['titulo', 'cuerpo', 'imagen_portada']

class PerfilUsuarioForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

entregaFinal/blog/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.http import HttpResponseRedirect, JsonResponse
from django.middleware.csrf import get_token
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import PerfilUsuarioForm, PublicacionForm, RegistrarForm
from .models import Comentario, Publicacion, Usuario

app_name='blog'

def home(request):
    login_error = request.COOKIES.get('login_error')
    if login_error:
        context = {'login_error': login_error}
    else:
        context = {}
    return render(request, 'home.html', context)


def registrar(request):
    if request.method == 'POST':
        form = RegistrarForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.password = make_password(form.cleaned_data['password1'])
            user.save()
            messages.success(request, 'Usuario creado correctamente.')
            return redirect('blog:Home')  # Redireccionar a la página de inicio
        else:
            # Agregar mensaje de error al campo de confirmación de contraseña
            form.add_error('password2', 'Las contraseñas no coinciden')
    else:
        form = RegistrarForm()
    return render(request, 'registrar.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url) 
            else:
                return redirect('Home')
        else:
            return HttpResponseRedirect(reverse('blog:Home') + '?login_error=Credenciales inválidas. Inténtalo de nuevo.')

    return JsonResponse({'success': False, 'message': 'Acceso no permitido.'})


def logout_view(request):
    logout(request)
    return redirect('blog:Home')  

@login_required
def crearPublicacion(request):
    if request.method == 'POST':
        form = PublicacionForm(request.POST, request.FILES)
        if form.is_valid():
            titulo = form.cleaned_data['titulo']
            cuerpo = form.cleaned_data['cuerpo']
            imagen_portada = form.cleaned_data['imagen_portada']
            publicacion = Publicacion(titulo=titulo, cuerpo=cuerpo, autor=request.user, imagen_portada=imagen_portada)
            publicacion.save()
            return redirect('blog:verPublicaciones')
    else:
        form = PublicacionForm(initial={'csrfmiddlewaretoken': get_token(request)})
    
    return render(request, 'publicacion.html')



def mostrarPublicaciones(request):
    publicaciones = Publicacion.objects.all()
    return render(request, 'publicaciones.html', {'publicaciones': publicaciones})


def detallePublicacion(request, pk):
    publicacion = get_object_or_404(Publicacion, pk=pk)
    return render(request, 'detallePublicacion.html', {'publicacion': publicacion})

@login_required
def agregarComentario(request, pk):
    publicacion = get_object_or_404(Publicacion, pk=pk)
    contenido = request.POST.get('contenido')
    autor = request.user

    if contenido:
        comentario = Comentario(publicacion=publicacion, autor=autor, contenido=contenido)
        comentario.save()

    next_url = request.POST.get('next')
    if next_url:
        return redirect(next_url)
    else:
        publicaciones = Publicacion.objects.all()
        return render(request, 'publicaciones.html', {'publicaciones': publicaciones})


@login_required
def eliminarComentario(request, pk):
    comentario = get_object_or_404(Comentario, pk=pk)
    if comentario.autor == request.user:
        comentario.delete()
        messages.success(request, 'Comentario eliminado correctamente.')
    else:
        messages.error(request, 'No tienes permiso para eliminar este comentario.')
    
    return redirect(request.META.get('HTTP_REFERER', 'Home'))

@login_required
def editarComentario(request, pk):
    comentario = get_object_or_404(Comentario, pk=pk)

    if request.method == 'POST':
        contenido = request.POST.get('contenido')
        if contenido:
            comentario.contenido = contenido
            comentario.save()
            messages.success(request, 'Comentario actualizado correctamente.')
        else:
            messages.error(request, 'El contenido del comentario no puede estar vacío.')

    return redirect('detallePublicacion', pk=comentario.publicacion.pk)


def filtrarPublicaciones(request):
    query = request.GET.get('q') 
    if query:
        publicaciones = Publicacion.objects.filter(titulo__icontains=query) | Publicacion.objects.filter(cuerpo__icontains=query) | Publicacion.objects.filter(autor__username__icontains=query)
    else:
        publicaciones = Publicacion.objects.all()
    return render(request, 'publicaciones.html', {'publicaciones': publicaciones})

@login_required
def perfil(request):
    user = request.user

    if request.method == 'POST':
        form = PerfilUsuarioForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('perfil')  
    else:
        form = PerfilUsuarioForm(instance=user)

    return render(request, 'perfil.html', {'form': form})

@login_required
def actualizarPerfil(request):
    if request.method == 'POST':
        # Obtener los datos del formulario
        email = request.POST['email']
        password = request.POST['password1']

        # Actualizar los datos del usuario
        user = request.user
        user.email = email
        if password:
            user.set_password(password)
        user.save()
        messages.success(request, 'Datos actualizados')
        
    else:
        messages.error(request, 'Datos no actualizados')
    
    return render(request, 'perfil.html')

@login_required
def eliminar_publicacion(request, publicacion_id):
    publicacion = Publicacion.objects.get(id=publicacion_id)
    if request.user == publicacion.autor:
        publicacion.delete()
        messages.success(request, 'Publicación eliminada.')
    else:
        messages.error(request, 'No tienes permiso para eliminar esta publicación.')
    
    return redirect(request.META.get('HTTP_REFERER', 'Home'))

def about(request):
    return render(request, 'about.html')

entregaFinal/blog/templates/about.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>Acerca de mi</h1>
    <p>
        Soy un desarrollador hace más de 4 años, me dedico a la creación de soluciones tecnológicas. 
        Tengo experiencia en el desarrollo de aplicaciones web con conocimientos en HTML, CSS, JavaScript, Angular, React, como también en la creación de servicios REST en java. 
        Mi objetivo es diseñar y desarrollar productos de alta calidad, centrados en la usabilidad y la experiencia del usuario. 
        Siempre estoy buscando nuevos desafíos y oportunidades para aprender y crecer en el campo de la tecnología.
    </p>
</div>
{% endblock content %}

entregaFinal/blog/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Final</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script src="https://kit.fontawesome.com/2ce8b68672.js" crossorigin="anonymous"></script>
    <script>
      document.addEventListener('DOMContentLoaded', function () {
          var currentUrl = window.location.href;
          var loginForm = document.getElementById('login-form');
          loginForm.action = "{% url 'blog:login' %}?next=" + encodeURIComponent(currentUrl);
      });
  </script>
  
</head>

<body class="bg-base">
    {% include 'components/navbar.html' %}
    
    <div class="container">
        <div class="row">
          <div class="col-1">
          </div>
          <div class="col-10">
            {% block content %}
    
            {% endblock content %} 
            {% if request.GET.login_error %}
              {% if user.is_authenticated %}
             
              {% else %}
                <div class="alert alert-danger">{{ request.GET.login_error }}</div>
              {% endif %}
            {% endif %}
          </div>
          <div class="col-1">
          </div>
        </div>
    </div>
    

    <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Ingrese sus credenciales</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form id="login-form" action="{% url 'blog:login' %}" method="POST">
              {% csrf_token %}
              <div class="mb-3">
                  <label for="username">Nombre de usuario</label>
                  <input type="text" id="username" name="username" class="form-control">
              </div>
              <div class="mb-3">
                  <label for="password">Contraseña</label>
                  <input type="password" id="password" name="password" class="form-control">
              </div>
              <input type="hidden" name="next" value="{{ request.GET.next }}">
              <div class="mb-3">              
                <button type="submit" class="btn btn-primary">Iniciar sesión</button>
              </div>
          </form>
          <div class="mb-3">              
            <a href="{% url 'blog:registrarUsuario' %}" ><button type="submit" class="btn btn-success">Registrar</button></a>
          </div>
          </div>
        </div>
      </div>
    </div>
      
    {% include 'components/footer.html' %}
</body>
</html>

entregaFinal/blog/templates/detallePublicacion.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>{{ publicacion.titulo }}</h1>
    <small>{{ publicacion.fecha }}</small>
    <p>{{ publicacion.cuerpo }}</p>
   

    <h2>Comentarios</h2>
    <div class="chat-container">
        {% if publicacion.comentarios.count > 0 %}
        <ul class="chat-list">
            {% for comentario in publicacion.comentarios.all %}
                <li class="chat-item {% if comentario.autor == request.user %}own{% else %}other{% endif %}">
                    <div class="chat-message">
                        <p class="chat-author">{{ comentario.autor }}</p>
                        <p class="chat-date">{{ comentario.fecha }}</p>
                        <p class="chat-content">{{ comentario.contenido }}</p>
                        {% if comentario.autor == request.user %}
                            <form method="POST" action="{% url 'blog:eliminarComentario' comentario.pk %}">
                                {% csrf_token %}
                                <input type="hidden" name="next2" value="{{ request.get_full_path }}">
                                <button type="submit" class="btn btn-link" >
                                    <i class="fa-solid fa-trash"></i>                              
                                </button>
                            </form>
                        {% endif %}
                    </div>
                   
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No hay comentarios.</p>
    {% endif %}
    </div>

    {% if user.is_authenticated %}
        <h5>Agregar comentario</h5>
        <form method="POST" action="{% url 'blog:agregarComentario' publicacion.id %}">
            {% csrf_token %}
            <div class="mb-3">
               <textarea name="contenido" rows="4" cols="50"></textarea>
            </div>
            <div class="mb-3">
                <input type="hidden" name="next" value="{{ request.get_full_path }}">
                <button type="submit" class="btn btn-primary">Enviar comentario</button>
            <div class="mb-3">
        </form>
    {% else %}
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#loginModal">Iniciar sesión para comentar</button>
    {% endif %}
</div>
<br>
<style>
    .chat-container {
        border: 1px solid #ccc;
        padding: 10px;
        max-width: 500px;
        margin-bottom: 20px;
    }
    .chat-list {
        list-style-type: none;
        padding: 0;
        margin: 0;
    }
    .chat-item {
        margin-bottom: 10px;
    }
    .chat-item .chat-message {
        padding: 10px;
        border-radius: 5px;
    }
    .chat-item.own .chat-message {
        background-color: #f0f0f0;
    }
    .chat-item.other .chat-message {
        background-color: #e0e0e0;
    }
    .chat-author {
        font-weight: bold;
    }
    .chat-date {
        font-size: 12px;
        color: #888;
        margin-bottom: 5px;
    }
    .chat-content {
        margin: 0;
    }
</style>


{% endblock content %}

entregaFinal/blog/templates/home.html
{% extends "base.html" %} 
{% load static %}
{% block content %}
<div class="d-flex justify-content-center mt-5 p-4 bg-white">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1 class="text-center text-primary mb-4">Bienvenidos al blog!</h1>
            </div>
        </div>
        <div class="row justify-content-center">
            {% if user.is_authenticated %}
            <div class="col-3">
                <div class="text-center">
                    <a href="{% url 'blog:crearPublicacion' %}"> <button type="button" class="btn btn-primary">Crear pubicación</button></a>
                </div>
            </div>
            {% endif %}
            <div class="col-3">
                <div class="text-center">
                    <a href="{% url 'blog:verPublicaciones' %}"><button type="button" class="btn btn-danger">Ver lista de foro</button></a>
                </div>
            </div>
            {% if user.is_authenticated %}
           
            {% else %}
            <div class="col-3">
                <div class="text-center">
                    <a href="{% url 'blog:registrarUsuario' %}" ><button type="button" class="btn btn-dark">Crear usuario</button></a>
                </div>
            </div>
            {% endif %}
            
        </div>
        <div class="row">
            <div class="col-12">
                
            </div>
        </div>
    </div>
</div>
<br>

{% endblock content %} 

entregaFinal/blog/templates/perfil.html
{% extends "base.html" %}

{% block content %}
<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                <img class="rounded-circle mt-5" width="150px" src="{% if user.profile_image %}{{ user.profile_image.url }}{% else %}https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg{% endif %}" alt="Imagen de perfil">
                <h4 class="text-right">Mis datos</h4>
                <span class="font-weight-bold">{{user.username}}</span>
                <span class="text-black-50">{{user.email}}</span>
                <span> </span>
            </div>
        </div>
        <div class="col-md-5 border-right">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Perfil usuario</h4>
                </div>
                <form id="perfil-form" action="{% url 'blog:actualizarPerfil' %}" method="POST">
                    {% csrf_token %}
                    <div class="row mt-2">
                        <div class="col-md-6">
                            <label class="labels">Username</label>
                            <input type="text" class="form-control" id="username" name="username" value="{{ user.username }}" disabled>
                            <input type="hidden" name="username" value="{{ user.username }}">
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-12">
                            <label class="labels">Correo electrónico</label>
                            <input type="email" class="form-control" name="email" value="{{ user.email }}">
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-12">
                            <label class="labels">Cambiar contraseña</label>
                            <input type="password" class="form-control" name="password1">
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-12">
                            <label class="labels">Imagen de perfil</label>
                            <input type="file" class="form-control" name="image_profile">
                        </div>
                    </div>
                    <div class="mt-5 text-center">
                        <button class="btn btn-primary profile-button" type="submit">Guardar cambios</button>
                    </div>
                </form>
            </div>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <div class="alert alert-danger">
                     <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                 </div>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

entregaFinal/blog/templates/publicacion.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>Crear nueva publicación</h1>
    <form method="post" action="{% url 'blog:crearPublicacion' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="titulo">Título</label>
            <input type="text" name="titulo" id="titulo" class="form-control">
        </div>
        <div class="mb-3">
            <label for="cuerpo">Cuerpo</label>
            <textarea name="cuerpo" id="cuerpo" class="form-control"></textarea>
        </div>
        <div class="mb-3">
            <label for="id_imagen_portada">Imagen de portada</label>
            <input type="file" name="imagen_portada" id="id_imagen_portada">
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Publicar</button>
        </div>
    </form>
</div>
{% endblock content %}

entregaFinal/blog/templates/publicaciones.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row mt-2">
        <a class="btn btn-link" href="{% url 'blog:Home' %}"><button class="btn btn-danger">volver</button></a>
    </div>
</div>

<div class="container">
    <h2>Temas publicados</h2>
    <form method="GET" action="{% url 'blog:filtraPublicaciones' %}">
        <div class="card mb-3">
            <input type="text" name="q" placeholder="Buscar por título, cuerpo o autor">
        </div>
        <button type="submit" class="btn btn-primary">Buscar</button>
        <button type="submit" class="btn btn-danger">Limpiar</button>
    </form>
    <hr>
    {% for publicacion in publicaciones %}
    <div class="card mb-3">
        <div class="row g-0">
          <div class="col-md-4">
             {% if publicacion.imagen_portada %}
                <img src="{{ publicacion.imagen_portada.url }}" class="img-fluid rounded-start" height="180px"
                width="180px" alt="Imagen de portada">
            {% endif %}
          </div>
          <div class="col-md-4">
            <div class="card-body">
              <h5 class="card-title">{{ publicacion.titulo }}</h5>
              <h5 class="card-title">Autor </h5><h6 class="card-subtitle mb-2 text-muted">{{ publicacion.autor.username }}</h6>
              <p class="card-text"><small class="text-muted">{{ publicacion.fecha }}</small></p>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card-body">     
                <a href="{% url 'blog:detallePublicacionPK' publicacion.id %}" class="btn btn-primary">Ver detalles</a>
                {% if publicacion.autor == request.user %}
                <a href="{% url 'blog:eliminarPublicacion' publicacion.id %}" class="btn btn-danger">Eliminar</a>
                {% endif %}
            </div>  
          </div>
        </div>
    </div>
    {% endfor %}
    
</div>
{% endblock content %}

entregaFinal/blog/templates/registrar.html
{% extends "base.html" %}
{% load static %} 

{% block content %}
<div class="container">
    <div class="row mt-2">
        <a class="btn btn-link" href="{% url 'blog:Home' %}"><button class="btn btn-danger">volver</button></a>
    </div>
</div>

<div class="d-flex justify-content-center mt-2 p-4 bg-white">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1 class="text-center text-primary mb-4">Registrar usuario</h1>
                <div class="modal-body">
                <form id="register-form" action="{% url 'blog:registrarUsuario' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <div class="mb-3">
                      <label for="username" class="form-label">Username</label>
                      <input type="text" class="form-control" id="username" name="username">
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label">Correo electrónico</label>
                        <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp">
                      </div>
                    <div class="mb-3">
                      <label for="password" class="form-label">contraseña</label>
                      <input type="password" class="form-control" id="password1" name="password1">
                    </div>
                    <div class="mb-3">
                        <label for="password2" class="form-label">Confirmar contraseña</label>
                        <input type="password" class="form-control" id="password2" name="password2">
                    </div>
                    <div class="row justify-content-center mt-4">
                        <div class="col-4">
                            <input type="submit" value="Crear usuario" class="btn btn-success w-100">
                        </div>
                    </div>
                  </form>
                <br>
            </div>
        </div>
    </div>
</div>

{% if form.non_field_errors %}
    <div class="alert alert-danger">
        {% for error in form.non_field_errors %}
            <p>{{ error }}</p>
        {% endfor %}
    </div>
{% endif %}

{% block scripts %}
<script>

    
    $(document).ready(function() {
        $('#register-form').submit(function(event) {
            // Evitar que el formulario se envíe normalmente
            event.preventDefault();

            // Realizar la petición AJAX al servidor
            $.ajax({
                url: $(this).attr('action'),
                type: $(this).attr('method'),
                data: new FormData(this),
                processData: false,
                contentType: false,
                success: function(response) {
                    // Mostrar el modal de éxito
                    $('#successModal').modal('show');

                    // Redirigir al inicio después de unos segundos
                    setTimeout(function() {
                        window.location.href = "{% url 'blog:Home' %}";  // Redireccionar al inicio
                    }, 2000);  // Esperar 2 segundos (2000 ms) antes de redireccionar
                },
                error: function(error) {
                    // Mostrar el mensaje de error
                    $('#error-message').text('Las contraseñas no coinciden');
                    $('#error-message').show();
                }
            });
        });
    });
</script>
{% endblock scripts %}

{% endblock content %}